### ISSUE TITLE
Duplicate?

### ISSUE THREAD

**Issue by derrickpelletier** [millsy/passport-strava#1]
Hey there, I just had a friend point me here out of confusion.

Is there are reason this module wasn't working for you? 
[derrickpelletier/passport-strava](https://github.com/derrickpelletier/passport-strava)

No point confusing users and having two identical modules maintained independently.

**Comment by millsy** [comment]
Actually I didn't find your solution until after I'd created this one but it served a purpose and actually I'll be extending this version slightly to incorporate all of the strava profile elements in to the user object.

**Comment by derrickpelletier** [comment]
I see, well if that's the case why wouldn't you just contribute that as an update to the existing module?

I'm by no means taking this personally, as all passport strategy repos are essentially just copies of a standard strategy.

But to put it simply, for the good of the npm ecosystem there is no need to fragment.

**Comment by millsy** [comment]
Once I have this doing what I need it to, I will certainly consider doing just that....right now it was (A) a learning exercise and (B) quicker & easier to control what was in the NPM by being in control of the code myself.

Thanks for taking the time to post...certainly not trying to cause fragmentation here

**Comment by derrickpelletier** [comment]
You can use your git url of your repo in your `package.json` rather than publishing to npm.

I.e. you could fork the existing `passport-strava` repo, modify it to your needs while still using it in your project without requiring it to be in npm.

**Comment by derrickpelletier** [comment]
see: https://docs.npmjs.com/files/package.json#github-urls
